apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: user-apps
spec:
  selector:
    app: application
  ports:
    - port: 9434
      targetPort: 9434
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: user-apps
type: Opaque
stringData:
  REDIS_ADDR: "redis.user-apps.svc.cluster.local:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: user-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: ali23uk/userprofile-service:95a53bc52e21b39faa215a14ddb168303e5e693a
          ports:
            - containerPort: 9434
          envFrom:
            - secretRef:
                name: app-secret