apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: application
  ports:
    - port: 9434
      targetPort: 9434
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  REDIS_ADDR: "redis:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
        - name: application
          image: ali506108/userprofile-service:latest
          ports:
            - containerPort: 9434
          envFrom:
            - secretRef:
                name: app-secret